primitive.boolean.truthy=true
primitive.boolean.false=false
primitive.number.zero=0
primitive.number.positive=187
primitive.number.negative=-187
primitive.number.float=1.87
primitive.string.sample=Une chaîne d?exemple
primitive.string.escaped="\nJe suis une chaîne avec des séquences d?échappement\""
primitive.string.multiline=\nJe suis une\nchaîne\nmultiligne\n\n
primitive.nullish=null
object.deeply.nested.structure.description=Une chaîne profondément imbriquée.
object.hybrid\\.flat\\.structure=Une chaîne partiellement imbriquée & partiellement plate
array=true, false, 0, 187, -187, 1.87, Une autre chaîne
only\\.flat\\.structure=Une chaîne super plate
missingValues.only.de_DE=Une valeur définie uniquement pour fr_FR.
duplicated.alpha=Une valeur dupliquée.
duplicated.bravo=Une valeur dupliquée.
