primitive.boolean.truthy=true
primitive.boolean.false=false
primitive.number.zero=0
primitive.number.positive=187
primitive.number.negative=-187
primitive.number.float=1.87
primitive.string.sample=Eine beispielhafte Zeichenkette
primitive.string.escaped="\nIch bin eine Zeichenkette mit Escape-Sequenzen\""
primitive.string.multiline=\nIch bin eine\nmehrzeilige\nZeichenkette\n\n
primitive.nullish=null
object.deeply.nested.structure.description=Eine tief verschachtelte Zeichenkette.
object.hybrid\\.flat\\.structure=Eine teils verschachtelte & teils flache Zeichenkette
array=true, false, 0, 187, -187, 1.87, Eine andere Zeichenkette
only\\.flat\\.structure=Eine super flache Zeichenkette
missingValues.only.de_DE=Ein Wert, der nur bei de_DE gesetzt ist.
duplicated.alpha=Ein doppelter Wert.
duplicated.bravo=Ein doppelter Wert.
